/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabelaPanel.java
 *
 * Created on 02/10/2011, 02:21:13
 */

package gd.views.principal;

/**
 *
 * @author Joao
 */
public class TabelaPanel extends javax.swing.JPanel {

    /** Creates new form TabelaPanel */
    public TabelaPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaButtonPanel = new javax.swing.JPanel();
        inserirRegistroButton = new InserirRegistroBotao();
        consultarRegistrosButton = new ConsultarRegistrosBotao();
        modificarRegistrosButton = new ModificarRegistrosBotao();
        removerRegistrosButton = new RemoverRegistrosBotao();
        tabelaScrollPane = new javax.swing.JScrollPane();
        tabelaTable = EntidadeTabela.instanciar(tabelaButtonPanel);

        setName("Form"); // NOI18N

        tabelaButtonPanel.setName("tabelaButtonPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gd.GerenciadorDados.class).getContext().getResourceMap(TabelaPanel.class);
        inserirRegistroButton.setText(resourceMap.getString("inserirRegistroButton.text")); // NOI18N
        inserirRegistroButton.setName("inserirRegistroButton"); // NOI18N

        consultarRegistrosButton.setText(resourceMap.getString("consultarRegistrosButton.text")); // NOI18N
        consultarRegistrosButton.setName("consultarRegistrosButton"); // NOI18N

        modificarRegistrosButton.setText(resourceMap.getString("modificarRegistrosButton.text")); // NOI18N
        modificarRegistrosButton.setName("modificarRegistrosButton"); // NOI18N

        removerRegistrosButton.setText(resourceMap.getString("removerRegistrosButton.text")); // NOI18N
        removerRegistrosButton.setName("removerRegistrosButton"); // NOI18N

        javax.swing.GroupLayout tabelaButtonPanelLayout = new javax.swing.GroupLayout(tabelaButtonPanel);
        tabelaButtonPanel.setLayout(tabelaButtonPanelLayout);
        tabelaButtonPanelLayout.setHorizontalGroup(
            tabelaButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inserirRegistroButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarRegistrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarRegistrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerRegistrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabelaButtonPanelLayout.setVerticalGroup(
            tabelaButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelaButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirRegistroButton)
                    .addComponent(consultarRegistrosButton)
                    .addComponent(modificarRegistrosButton)
                    .addComponent(removerRegistrosButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaScrollPane.setName("tabelaScrollPane"); // NOI18N

        tabelaTable.setName("tabelaTable"); // NOI18N
        tabelaScrollPane.setViewportView(tabelaTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tabelaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarRegistrosButton;
    private javax.swing.JButton inserirRegistroButton;
    private javax.swing.JButton modificarRegistrosButton;
    private javax.swing.JButton removerRegistrosButton;
    private javax.swing.JPanel tabelaButtonPanel;
    private javax.swing.JScrollPane tabelaScrollPane;
    private javax.swing.JTable tabelaTable;
    // End of variables declaration//GEN-END:variables

}
