/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabelasPanel.java
 *
 * Created on 02/10/2011, 02:11:05
 */

package gd.views.principal;

/**
 *
 * @author Joao
 */
public class TabelasPanel extends javax.swing.JPanel {

    /** Creates new form TabelasPanel */
    public TabelasPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelasLabel = new javax.swing.JLabel();
        tabelasScrollPane = new javax.swing.JScrollPane();
        tabelasList = TabelasLista.getInstancia();
        tabelasButtonPanel = new javax.swing.JPanel();
        criarTabelaButton = new CriarTabelaBotao();
        excluirTabelaButton = new ExcluirTabelaBotao();
        criarReferenciaButton = new CriarReferenciaBotao();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gd.GerenciadorDados.class).getContext().getResourceMap(TabelasPanel.class);
        tabelasLabel.setText(resourceMap.getString("tabelasLabel.text")); // NOI18N
        tabelasLabel.setName("tabelasLabel"); // NOI18N

        tabelasScrollPane.setName("tabelasScrollPane"); // NOI18N

        tabelasList.setName("tabelasList"); // NOI18N
        tabelasScrollPane.setViewportView(tabelasList);

        tabelasButtonPanel.setName("tabelasButtonPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(gd.GerenciadorDados.class).getContext().getActionMap(TabelasPanel.class, this);
        criarTabelaButton.setAction(actionMap.get("showCriarTabelaBox")); // NOI18N
        criarTabelaButton.setText(resourceMap.getString("criarTabelaButton.text")); // NOI18N

        excluirTabelaButton.setText(resourceMap.getString("excluirTabelaButton.text")); // NOI18N
        excluirTabelaButton.setName("excluirTabelaButton"); // NOI18N

        criarReferenciaButton.setAction(actionMap.get("showCriarReferenciaView")); // NOI18N
        criarReferenciaButton.setText(resourceMap.getString("criarReferenciaButton.text")); // NOI18N
        criarReferenciaButton.setName("criarReferenciaButton"); // NOI18N

        javax.swing.GroupLayout tabelasButtonPanelLayout = new javax.swing.GroupLayout(tabelasButtonPanel);
        tabelasButtonPanel.setLayout(tabelasButtonPanelLayout);
        tabelasButtonPanelLayout.setHorizontalGroup(
            tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelasButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(criarTabelaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(tabelasButtonPanelLayout.createSequentialGroup()
                        .addComponent(criarReferenciaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirTabelaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabelasButtonPanelLayout.setVerticalGroup(
            tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelasButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criarTabelaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirTabelaButton)
                    .addComponent(criarReferenciaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelasButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(tabelasLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelasButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarReferenciaButton;
    private javax.swing.JButton criarTabelaButton;
    private javax.swing.JButton excluirTabelaButton;
    private javax.swing.JPanel tabelasButtonPanel;
    private javax.swing.JLabel tabelasLabel;
    private javax.swing.JList tabelasList;
    private javax.swing.JScrollPane tabelasScrollPane;
    // End of variables declaration//GEN-END:variables

}
