/*
 * GerenciadorDadosAboutBox.java
 */

package dm.views;

import dm.controllers.WindowController;
import dm.controllers.TableController;
import dm.exceptions.ModelException;
import org.jdesktop.application.Action;

public class CreateTableView extends javax.swing.JDialog {

    TableList tables = null;

    public CreateTableView(java.awt.Frame parent, TableList tables) {
        super(parent);
        this.tables = tables;

        initComponents();

        attributeTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelA = new javax.swing.JPanel();
        attributeScrollPane = new javax.swing.JScrollPane();
        attributeTable = new dm.views.AttributeTable();
        removeButton = new javax.swing.JButton();
        painelB = new javax.swing.JPanel();
        addAttributePanel = new javax.swing.JPanel();
        attributeNameLabel = new javax.swing.JLabel();
        attributeNameTextField = new javax.swing.JTextField();
        attributeTypeLabel = new javax.swing.JLabel();
        attributeTypeComboBox = new dm.views.AttributeOptionsComboBox();
        addButton = new javax.swing.JButton();
        tableNamePanel = new javax.swing.JPanel();
        tableNameLabel = new javax.swing.JLabel();
        tableNameTextField = new javax.swing.JTextField();
        createPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dm.DataManager.class).getContext().getResourceMap(CreateTableView.class);
        setTitle(resourceMap.getString("aboutBox.title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        painelA.setName("painelA"); // NOI18N

        attributeScrollPane.setName("attributeScrollPane"); // NOI18N

        attributeTable.setName("attributeTable"); // NOI18N
        attributeScrollPane.setViewportView(attributeTable);

        removeButton.setText(resourceMap.getString("removeButton.text")); // NOI18N
        removeButton.setName("removeButton"); // NOI18N
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attributeRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelALayout = new javax.swing.GroupLayout(painelA);
        painelA.setLayout(painelALayout);
        painelALayout.setHorizontalGroup(
            painelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attributeScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(removeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelALayout.setVerticalGroup(
            painelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attributeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeButton)
                .addContainerGap())
        );

        painelB.setName("painelB"); // NOI18N

        addAttributePanel.setName("addAttributePanel"); // NOI18N

        attributeNameLabel.setText(resourceMap.getString("attributeNameLabel.text")); // NOI18N
        attributeNameLabel.setName("attributeNameLabel"); // NOI18N

        attributeNameTextField.setName("attributeNameTextField"); // NOI18N

        attributeTypeLabel.setText(resourceMap.getString("attributeTypeLabel.text")); // NOI18N
        attributeTypeLabel.setName("attributeTypeLabel"); // NOI18N

        attributeTypeComboBox.setName("attributeTypeComboBox"); // NOI18N

        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setName("addButton"); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttributeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addAttributePanelLayout = new javax.swing.GroupLayout(addAttributePanel);
        addAttributePanel.setLayout(addAttributePanelLayout);
        addAttributePanelLayout.setHorizontalGroup(
            addAttributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAttributePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addAttributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attributeNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(attributeNameLabel)
                    .addComponent(attributeTypeLabel)
                    .addComponent(attributeTypeComboBox, 0, 222, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        addAttributePanelLayout.setVerticalGroup(
            addAttributePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAttributePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attributeNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        tableNamePanel.setName("tableNamePanel"); // NOI18N

        tableNameLabel.setText(resourceMap.getString("tableNameLabel.text")); // NOI18N
        tableNameLabel.setName("tableNameLabel"); // NOI18N

        tableNameTextField.setName("tableNameTextField"); // NOI18N

        javax.swing.GroupLayout tableNamePanelLayout = new javax.swing.GroupLayout(tableNamePanel);
        tableNamePanel.setLayout(tableNamePanelLayout);
        tableNamePanelLayout.setHorizontalGroup(
            tableNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableNameLabel)
                    .addComponent(tableNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        tableNamePanelLayout.setVerticalGroup(
            tableNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createPanel.setName("createPanel"); // NOI18N

        createButton.setText(resourceMap.getString("createButton.text")); // NOI18N
        createButton.setName("createButton"); // NOI18N
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelBLayout = new javax.swing.GroupLayout(painelB);
        painelB.setLayout(painelBLayout);
        painelBLayout.setHorizontalGroup(
            painelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tableNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addAttributePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelBLayout.setVerticalGroup(
            painelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAttributePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(createPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAttributeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttributeActionPerformed
        TableController.insertAttribute(
            (AttributeTable) attributeTable,
            attributeNameTextField.getText(),
            (String) attributeTypeComboBox.getSelectedItem()
        );
    }//GEN-LAST:event_addAttributeActionPerformed

    private void attributeRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attributeRemoveActionPerformed
        TableController.removeAttribute((AttributeTable) attributeTable);
    }//GEN-LAST:event_attributeRemoveActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        try {
            TableController.createTable(attributeTable.getModel(), tableNameTextField.getText());
            this.dispose();
            tables.update();
        } catch (ModelException ex) {
            ex.execute();
        }
    }//GEN-LAST:event_createActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        WindowController.closeDialog(this);
    }//GEN-LAST:event_cancelActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addAttributePanel;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel attributeNameLabel;
    private javax.swing.JTextField attributeNameTextField;
    private javax.swing.JScrollPane attributeScrollPane;
    private javax.swing.JTable attributeTable;
    private javax.swing.JComboBox attributeTypeComboBox;
    private javax.swing.JLabel attributeTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel createPanel;
    private javax.swing.JPanel painelA;
    private javax.swing.JPanel painelB;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel tableNameLabel;
    private javax.swing.JPanel tableNamePanel;
    private javax.swing.JTextField tableNameTextField;
    // End of variables declaration//GEN-END:variables
    
}
