/*
 * GerenciadorDadosAboutBox.java
 */

package gd.views;

import gd.controllers.WindowController;
import gd.controllers.TableController;
import gd.exceptions.ModelException;
import gd.views.base.NotEditableComboBox;
import org.jdesktop.application.Action;

public class CreateReferenceView extends javax.swing.JDialog {

    private TableList tables = null;

    public CreateReferenceView(java.awt.Frame parent, TableList tables) {
        super(parent);
        this.tables = tables;
        initComponents();
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attributeLabel = new javax.swing.JLabel();
        attributeComboBox = new NotEditableComboBox();
        entityLabel = new javax.swing.JLabel();
        entityComboBox = new gd.views.EntityComboBox(attributeComboBox);
        pkLabel = new javax.swing.JLabel();
        pkComboBox = new NotEditableComboBox();
        referencedLabel = new javax.swing.JLabel();
        referencedComboBox = new gd.views.EntityComboBox(pkComboBox);
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gd.DataManager.class).getContext().getResourceMap(CreateReferenceView.class);
        attributeLabel.setText(resourceMap.getString("attributeLabel.text")); // NOI18N
        attributeLabel.setName("attributeLabel"); // NOI18N

        attributeComboBox.setName("attributeComboBox"); // NOI18N

        entityLabel.setText(resourceMap.getString("entityLabel.text")); // NOI18N
        entityLabel.setName("entityLabel"); // NOI18N

        entityComboBox.setName("entityComboBox"); // NOI18N

        pkLabel.setText(resourceMap.getString("pkLabel.text")); // NOI18N
        pkLabel.setName("pkLabel"); // NOI18N

        pkComboBox.setName("pkComboBox"); // NOI18N

        referencedLabel.setText(resourceMap.getString("referencedLabel.text")); // NOI18N
        referencedLabel.setName("referencedLabel"); // NOI18N

        referencedComboBox.setName("referencedComboBox"); // NOI18N

        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setName("addButton"); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pkComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 247, Short.MAX_VALUE)
                            .addComponent(referencedComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 247, Short.MAX_VALUE)
                            .addComponent(attributeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pkLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referencedLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entityLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entityComboBox, 0, 247, Short.MAX_VALUE)
                            .addComponent(attributeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 247, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referencedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referencedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        try {
            TableController.createReference(
                (String)entityComboBox.getSelectedItem(),
                (String)attributeComboBox.getSelectedItem(),
                (String)referencedComboBox.getSelectedItem(),
                (String)pkComboBox.getSelectedItem()
            );
            WindowController.closeDialog(this);
        } catch (ModelException ex) {
            ex.execute();
        }
        tables.update();
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        WindowController.closeDialog(this);
    }//GEN-LAST:event_cancelActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox attributeComboBox;
    private javax.swing.JLabel attributeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox entityComboBox;
    private javax.swing.JLabel entityLabel;
    private javax.swing.JComboBox pkComboBox;
    private javax.swing.JLabel pkLabel;
    private javax.swing.JComboBox referencedComboBox;
    private javax.swing.JLabel referencedLabel;
    // End of variables declaration//GEN-END:variables
    
}
