/*
 * GerenciadorDadosAboutBox.java
 */

package gd.views;

import gd.controllers.CloseDialogCommand;
import gd.controllers.criarreferencia.AdicionarReferenciaCommand;
import gd.views.base.ComboBoxNaoEditavel;
import org.jdesktop.application.Action;

public class CriarReferenciaView extends javax.swing.JDialog {

    ListaTabelas tabelas = null;

    public CriarReferenciaView(java.awt.Frame parent, ListaTabelas tabelas) {
        super(parent);
        this.tabelas = tabelas;
        initComponents();
   //     getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atributoLabel = new javax.swing.JLabel();
        atributoComboBox = new ComboBoxNaoEditavel();
        tabelaLabel = new javax.swing.JLabel();
        tabelaComboBox = new gd.views.CriarReferenciaTabelasCombo(atributoComboBox);
        codigoLabel = new javax.swing.JLabel();
        codigoComboBox = new ComboBoxNaoEditavel();
        buscaLabel = new javax.swing.JLabel();
        buscaComboBox = new ComboBoxNaoEditavel();
        referenciadaLabel = new javax.swing.JLabel();
        referenciadaComboBox = new CriarReferenciaReferenciadasCombo(codigoComboBox, buscaComboBox);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gd.GerenciadorDados.class).getContext().getResourceMap(CriarReferenciaView.class);
        atributoLabel.setText(resourceMap.getString("atributoLabel.text")); // NOI18N
        atributoLabel.setName("atributoLabel"); // NOI18N

        atributoComboBox.setName("atributoComboBox"); // NOI18N

        tabelaLabel.setText(resourceMap.getString("tabelaLabel.text")); // NOI18N
        tabelaLabel.setName("tabelaLabel"); // NOI18N

        tabelaComboBox.setName("tabelaComboBox"); // NOI18N

        codigoLabel.setText(resourceMap.getString("codigoLabel.text")); // NOI18N
        codigoLabel.setName("codigoLabel"); // NOI18N

        codigoComboBox.setName("codigoComboBox"); // NOI18N

        buscaLabel.setText(resourceMap.getString("buscaLabel.text")); // NOI18N
        buscaLabel.setName("buscaLabel"); // NOI18N

        buscaComboBox.setName("buscaComboBox"); // NOI18N

        referenciadaLabel.setText(resourceMap.getString("referenciadaLabel.text")); // NOI18N
        referenciadaLabel.setName("referenciadaLabel"); // NOI18N

        referenciadaComboBox.setName("referenciadaComboBox"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 247, Short.MAX_VALUE)
                            .addComponent(referenciadaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 247, Short.MAX_VALUE)
                            .addComponent(atributoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referenciadaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabelaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabelaComboBox, 0, 247, Short.MAX_VALUE)
                            .addComponent(atributoComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 247, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscaComboBox, 0, 247, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atributoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atributoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciadaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciadaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(buscaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        new AdicionarReferenciaCommand(this, tabelaComboBox, atributoComboBox, referenciadaComboBox, codigoComboBox, buscaComboBox).execute();
        tabelas.atualizar();
    }//GEN-LAST:event_okActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        new CloseDialogCommand(this).execute();
    }//GEN-LAST:event_cancelarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox atributoComboBox;
    private javax.swing.JLabel atributoLabel;
    private javax.swing.JComboBox buscaComboBox;
    private javax.swing.JLabel buscaLabel;
    private javax.swing.JComboBox codigoComboBox;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox referenciadaComboBox;
    private javax.swing.JLabel referenciadaLabel;
    private javax.swing.JComboBox tabelaComboBox;
    private javax.swing.JLabel tabelaLabel;
    // End of variables declaration//GEN-END:variables
    
}
