/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipalView.java
 *
 * Created on 11/10/2011, 17:44:54
 */

package gd.views;

import gd.GerenciadorDados;
import gd.controllers.OpenDialogCommand;
import gd.controllers.TabelasController;
import gd.views.tabelaer.TabelaPrincipal;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joao
 */
public class TelaPrincipalView extends JFrame {


    private static TelaPrincipalView instancia = null;

    public static TelaPrincipalView getInstance() {
        if (TelaPrincipalView.instancia == null)
            TelaPrincipalView.instancia = new TelaPrincipalView();
        return TelaPrincipalView.instancia;
    }

    /** Creates new form TelaPrincipalView */
    public TelaPrincipalView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        divisaoPrincipal = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        tabelasLabel = new javax.swing.JLabel();
        tabelasScrollPane = new javax.swing.JScrollPane();
        tabelasList = new ListaTabelas();
        tabelasButtonPanel = new javax.swing.JPanel();
        criarTabelaButton = new javax.swing.JButton();
        excluirTabelaButton = new javax.swing.JButton();
        criarReferenciaButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tabelaButtonPanel = new javax.swing.JPanel();
        inserirRegistroButton = new javax.swing.JButton();
        consultarRegistrosButton = new javax.swing.JButton();
        modificarRegistrosButton = new javax.swing.JButton();
        removerRegistrosButton = new javax.swing.JButton();
        tabelaScrollPane = new javax.swing.JScrollPane();
        tabelaTable = gd.views.tabelaer.TabelaPrincipal.instanciar(tabelaButtonPanel);
        menuBar = new javax.swing.JMenuBar();
        arquivoMenu = new javax.swing.JMenu();
        criarTabelaMenuItem = new javax.swing.JMenuItem();
        criarReferenciaMenuItem = new javax.swing.JMenuItem();
        excluirTabelaMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sairMenuItem = new javax.swing.JMenuItem();
        tabelaMenu = new javax.swing.JMenu();
        inserirRegistroMenuItem = new javax.swing.JMenuItem();
        consultarRegistrosMenuItem = new javax.swing.JMenuItem();
        modificarRegistrosMenuItem = new javax.swing.JMenuItem();
        removerRegistrosMenuItem = new javax.swing.JMenuItem();
        sobreMenu = new javax.swing.JMenu();
        sobreMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gd.GerenciadorDados.class).getContext().getResourceMap(TelaPrincipalView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 0));
        setName("Form"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N

        divisaoPrincipal.setDividerLocation(175);
        divisaoPrincipal.setName("divisaoPrincipal"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        tabelasLabel.setText(resourceMap.getString("tabelasLabel.text")); // NOI18N
        tabelasLabel.setName("tabelasLabel"); // NOI18N

        tabelasScrollPane.setName("tabelasScrollPane"); // NOI18N

        tabelasList.setName("tabelasList"); // NOI18N
        tabelasScrollPane.setViewportView(tabelasList);

        tabelasButtonPanel.setName("tabelasButtonPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(gd.GerenciadorDados.class).getContext().getActionMap(TelaPrincipalView.class, this);
        criarTabelaButton.setAction(actionMap.get("showCriarTabelaBox")); // NOI18N
        criarTabelaButton.setText(resourceMap.getString("criarTabelaButton.text")); // NOI18N
        criarTabelaButton.setName("criarTabelaButton"); // NOI18N
        criarTabelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarTabelaActionPerformed(evt);
            }
        });

        excluirTabelaButton.setText(resourceMap.getString("excluirTabelaButton.text")); // NOI18N
        excluirTabelaButton.setName("excluirTabelaButton"); // NOI18N
        excluirTabelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTabelaActionPerformed(evt);
            }
        });

        criarReferenciaButton.setAction(actionMap.get("showCriarReferenciaView")); // NOI18N
        criarReferenciaButton.setText(resourceMap.getString("criarReferenciaButton.text")); // NOI18N
        criarReferenciaButton.setName("criarReferenciaButton"); // NOI18N
        criarReferenciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarReferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabelasButtonPanelLayout = new javax.swing.GroupLayout(tabelasButtonPanel);
        tabelasButtonPanel.setLayout(tabelasButtonPanelLayout);
        tabelasButtonPanelLayout.setHorizontalGroup(
            tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelasButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(criarTabelaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGroup(tabelasButtonPanelLayout.createSequentialGroup()
                        .addComponent(criarReferenciaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirTabelaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabelasButtonPanelLayout.setVerticalGroup(
            tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelasButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criarTabelaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabelasButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirTabelaButton)
                    .addComponent(criarReferenciaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelasButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(tabelasLabel))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelasButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        divisaoPrincipal.setLeftComponent(jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        tabelaButtonPanel.setName("tabelaButtonPanel"); // NOI18N

        inserirRegistroButton.setText(resourceMap.getString("inserirRegistroButton.text")); // NOI18N
        inserirRegistroButton.setName("inserirRegistroButton"); // NOI18N
        inserirRegistroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirRegistroActionPerformed(evt);
            }
        });

        consultarRegistrosButton.setText(resourceMap.getString("consultarRegistrosButton.text")); // NOI18N
        consultarRegistrosButton.setName("consultarRegistrosButton"); // NOI18N
        consultarRegistrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarRegistrosActionPerformed(evt);
            }
        });

        modificarRegistrosButton.setText(resourceMap.getString("modificarRegistrosButton.text")); // NOI18N
        modificarRegistrosButton.setName("modificarRegistrosButton"); // NOI18N
        modificarRegistrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarRegistrosActionPerformed(evt);
            }
        });

        removerRegistrosButton.setText(resourceMap.getString("removerRegistrosButton.text")); // NOI18N
        removerRegistrosButton.setName("removerRegistrosButton"); // NOI18N
        removerRegistrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerRegistrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabelaButtonPanelLayout = new javax.swing.GroupLayout(tabelaButtonPanel);
        tabelaButtonPanel.setLayout(tabelaButtonPanelLayout);
        tabelaButtonPanelLayout.setHorizontalGroup(
            tabelaButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inserirRegistroButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarRegistrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarRegistrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerRegistrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabelaButtonPanelLayout.setVerticalGroup(
            tabelaButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelaButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirRegistroButton)
                    .addComponent(consultarRegistrosButton)
                    .addComponent(modificarRegistrosButton)
                    .addComponent(removerRegistrosButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaScrollPane.setName("tabelaScrollPane"); // NOI18N

        tabelaTable.setName("tabelaTable"); // NOI18N
        tabelaScrollPane.setViewportView(tabelaTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tabelaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabelaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        divisaoPrincipal.setRightComponent(jPanel2);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisaoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisaoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        arquivoMenu.setText(resourceMap.getString("arquivoMenu.text")); // NOI18N
        arquivoMenu.setName("arquivoMenu"); // NOI18N

        criarTabelaMenuItem.setText(resourceMap.getString("criarTabelaMenuItem.text")); // NOI18N
        criarTabelaMenuItem.setName("criarTabelaMenuItem"); // NOI18N
        criarTabelaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarTabelaActionPerformed(evt);
            }
        });
        arquivoMenu.add(criarTabelaMenuItem);

        criarReferenciaMenuItem.setText(resourceMap.getString("criarReferenciaMenuItem.text")); // NOI18N
        criarReferenciaMenuItem.setName("criarReferenciaMenuItem"); // NOI18N
        criarReferenciaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarReferenciaActionPerformed(evt);
            }
        });
        arquivoMenu.add(criarReferenciaMenuItem);

        excluirTabelaMenuItem.setText(resourceMap.getString("excluirTabelaMenuItem.text")); // NOI18N
        excluirTabelaMenuItem.setName("excluirTabelaMenuItem"); // NOI18N
        excluirTabelaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirTabelaActionPerformed(evt);
            }
        });
        arquivoMenu.add(excluirTabelaMenuItem);

        jSeparator1.setName("jSeparator1"); // NOI18N
        arquivoMenu.add(jSeparator1);

        sairMenuItem.setText(resourceMap.getString("sairMenuItem.text")); // NOI18N
        sairMenuItem.setName("sairMenuItem"); // NOI18N
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        arquivoMenu.add(sairMenuItem);

        menuBar.add(arquivoMenu);

        tabelaMenu.setText(resourceMap.getString("tabelaMenu.text")); // NOI18N
        tabelaMenu.setName("tabelaMenu"); // NOI18N
        tabelaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirRegistroActionPerformed(evt);
            }
        });

        inserirRegistroMenuItem.setText(resourceMap.getString("inserirRegistroMenuItem.text")); // NOI18N
        inserirRegistroMenuItem.setName("inserirRegistroMenuItem"); // NOI18N
        inserirRegistroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirRegistroActionPerformed(evt);
            }
        });
        tabelaMenu.add(inserirRegistroMenuItem);

        consultarRegistrosMenuItem.setText(resourceMap.getString("consultarRegistrosMenuItem.text")); // NOI18N
        consultarRegistrosMenuItem.setName("consultarRegistrosMenuItem"); // NOI18N
        consultarRegistrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarRegistrosActionPerformed(evt);
            }
        });
        tabelaMenu.add(consultarRegistrosMenuItem);

        modificarRegistrosMenuItem.setText(resourceMap.getString("modificarRegistrosMenuItem.text")); // NOI18N
        modificarRegistrosMenuItem.setName("modificarRegistrosMenuItem"); // NOI18N
        modificarRegistrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarRegistrosActionPerformed(evt);
            }
        });
        tabelaMenu.add(modificarRegistrosMenuItem);

        removerRegistrosMenuItem.setText(resourceMap.getString("removerRegistrosMenuItem.text")); // NOI18N
        removerRegistrosMenuItem.setName("removerRegistrosMenuItem"); // NOI18N
        removerRegistrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerRegistrosActionPerformed(evt);
            }
        });
        tabelaMenu.add(removerRegistrosMenuItem);

        menuBar.add(tabelaMenu);

        sobreMenu.setText(resourceMap.getString("sobreMenu.text")); // NOI18N
        sobreMenu.setName("sobreMenu"); // NOI18N

        sobreMenuItem.setText(resourceMap.getString("sobreMenuItem.text")); // NOI18N
        sobreMenuItem.setName("sobreMenuItem"); // NOI18N
        sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuItemActionPerformed(evt);
            }
        });
        sobreMenu.add(sobreMenuItem);

        menuBar.add(sobreMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void criarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarTabelaActionPerformed
        new OpenDialogCommand(new CriarTabelaView(GerenciadorDados.getApplication().getMainFrame(), (ListaTabelas) tabelasList)).execute();
    }//GEN-LAST:event_criarTabelaActionPerformed

    private void criarReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarReferenciaActionPerformed
        new OpenDialogCommand(new CriarReferenciaView(GerenciadorDados.getApplication().getMainFrame(), (ListaTabelas) tabelasList)).execute();
    }//GEN-LAST:event_criarReferenciaActionPerformed

    private void excluirTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirTabelaActionPerformed
        ListaTabelas tabela = (ListaTabelas) tabelasList;
        TabelasController.excluirTabela(tabela.getSelectedName());
        tabela.atualizar();
    }//GEN-LAST:event_excluirTabelaActionPerformed

    private void inserirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirRegistroActionPerformed
        ((TabelaPrincipal) tabelaTable).addRow(new Object[]{});
    }//GEN-LAST:event_inserirRegistroActionPerformed

    private void consultarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarRegistrosActionPerformed
        new OpenDialogCommand(new ConsultarView(GerenciadorDados.getApplication().getMainFrame())).execute();
    }//GEN-LAST:event_consultarRegistrosActionPerformed

    private void modificarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarRegistrosActionPerformed
        new OpenDialogCommand(new ModificarView(GerenciadorDados.getApplication().getMainFrame())).execute();
    }//GEN-LAST:event_modificarRegistrosActionPerformed

    private void removerRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerRegistrosActionPerformed
        new OpenDialogCommand(new ConsultarView(GerenciadorDados.getApplication().getMainFrame())).execute();
    }//GEN-LAST:event_removerRegistrosActionPerformed

    private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuItemActionPerformed
        new OpenDialogCommand(new SobreView(GerenciadorDados.getApplication().getMainFrame())).execute();
    }//GEN-LAST:event_sobreMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu arquivoMenu;
    private javax.swing.JButton consultarRegistrosButton;
    private javax.swing.JMenuItem consultarRegistrosMenuItem;
    private javax.swing.JButton criarReferenciaButton;
    private javax.swing.JMenuItem criarReferenciaMenuItem;
    private javax.swing.JButton criarTabelaButton;
    private javax.swing.JMenuItem criarTabelaMenuItem;
    private javax.swing.JSplitPane divisaoPrincipal;
    private javax.swing.JButton excluirTabelaButton;
    private javax.swing.JMenuItem excluirTabelaMenuItem;
    private javax.swing.JButton inserirRegistroButton;
    private javax.swing.JMenuItem inserirRegistroMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton modificarRegistrosButton;
    private javax.swing.JMenuItem modificarRegistrosMenuItem;
    private javax.swing.JButton removerRegistrosButton;
    private javax.swing.JMenuItem removerRegistrosMenuItem;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenu sobreMenu;
    private javax.swing.JMenuItem sobreMenuItem;
    private javax.swing.JPanel tabelaButtonPanel;
    private javax.swing.JMenu tabelaMenu;
    private javax.swing.JScrollPane tabelaScrollPane;
    private javax.swing.JTable tabelaTable;
    private javax.swing.JPanel tabelasButtonPanel;
    private javax.swing.JLabel tabelasLabel;
    private javax.swing.JList tabelasList;
    private javax.swing.JScrollPane tabelasScrollPane;
    // End of variables declaration//GEN-END:variables

}
